version: '3.8'

services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ordenes_user
      POSTGRES_PASSWORD: ordenes_pass
      POSTGRES_DB: ordenesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
